### ISSUE TITLE
org.w3c.dom.DOMException: NAMESPACE_ERR

### ISSUE THREAD

**Issue by meshkin** [amouat/diffxml#1]
Hi, 
when i diff two bellow documents, get this error:
doc1 => "<body><span >new</span></body>"
doc2 => "<body><p><span>doc<span xml:id="tan_87c69qu3evta">dd</span>ff</span></p></body>"
error => 
Exception in thread "main" org.w3c.dom.DOMException: NAMESPACE_ERR: An attempt is made to create or change an object in a way which is incorrect with regard to namespaces.
    at com.sun.org.apache.xerces.internal.dom.ElementNSImpl.setName(ElementNSImpl.java:109)
    at com.sun.org.apache.xerces.internal.dom.ElementNSImpl.<init>(ElementNSImpl.java:84)
    at com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.createElementNS(CoreDocumentImpl.java:2099)
    at org.diffxml.diffxml.fmes.EditScript.doUpdate(EditScript.java:169)
    at org.diffxml.diffxml.fmes.EditScript.create(EditScript.java:129)
    at org.diffxml.diffxml.fmes.Fmes.diff(Fmes.java:150)
    at tanaafosdiffpatch.DiffPatch.diff(DiffPatch.java:50)
    at tanaafosdiffpatch.DiffPatch.getDelta(DiffPatch.java:44)
    at tanaafosdiffpatch.DiffPatch.main(DiffPatch.java:27)
Java Result: 1
thanks

**Comment by amouat** [comment]
Err, those don't look like XML documents?

**Comment by meshkin** [comment]
the documents are xml.
the error caused by xml:id attribute!
assume bellow docs:
doc1 => '<b><c>new</c></b>'
doc2 => '<b><f><h>yy<h xml:id="m87c69qu3evta" >fgh</h>dffdg</h></f></b>'

**Comment by meshkin** [comment]
please see source of my comments, my xml struct are shown in it.

**Comment by amouat** [comment]
Hmm, this works for me:

```
$ cat t1.xml
<body><span >new</span></body>
$ cat t2.xml
<body><p><span>doc<span xml:id="tan_87c69qu3evta">dd</span>ff</span></p></body>
$ ./diffxml.sh t1.xml t2.xml 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<delta xmlns="http://www.adrianmouat.com/dul">
<insert childno="1" name="p" nodetype="1" ns="" parent="/node()[1]"/>
<move childno="1" new_charpos="1" node="/node()[1]/node()[2]" old_charpos="1" parent="/node()[1]/node()[1]"/>
<insert childno="1" nodetype="3" parent="/node()[1]/node()[1]/node()[1]">doc</insert>
<insert charpos="4" childno="2" name="span" nodetype="1" ns="" parent="/node()[1]/node()[1]/node()[1]"/>
<insert name="id" nodetype="2" ns="http://www.w3.org/XML/1998/namespace" parent="/node()[1]/node()[1]/node()[1]/node()[2]">tan_87c69qu3evta</insert>
<insert childno="3" nodetype="3" parent="/node()[1]/node()[1]/node()[1]">ff</insert>
<insert childno="1" nodetype="3" parent="/node()[1]/node()[1]/node()[1]/node()[2]">dd</insert>
<delete charpos="3" length="3" node="/node()[1]/node()[1]/node()[1]/node()[3]"/>
```

</delta>

Can you please let me know which version of Java and diffxml you're using?

**Comment by meshkin** [comment]
my java version:
openjdk version "1.8.0_60"
OpenJDK Runtime Environment (build 1.8.0_60-b27)
OpenJDK 64-Bit Server VM (build 25.60-b23, mixed mode)
and cloned the latest version of diffxml.
when I run "./diffxml.sh test1a.xml test2a.xml", got the bellow error:
Error: Could not find or load main class org.diffxml.diffxml.DiffXML

**Comment by amouat** [comment]
So how were you running it before?

You need to build the code if you grab it from source: 

```
$ ant jarDiffXML
```

That should have been explained in the README, sorry.

**Comment by meshkin** [comment]
I download your source and edit the java/org/diffxml/diffxml file and add following line end of Diff interface:
Document diff(final Document f1, final Document f2) throws DiffException;
then I build the source and make the jar file. the link : (http://www.mediafire.com/download/0xfdvp7kxkajdwc/diffxml.zip)
then I use it in my other projects. in all of cases work very good, but when one of docs has xml:\* the above error throw.

**Comment by meshkin** [comment]
ant jarDiffXML
Buildfile: /home/masoud/diffxml-master/build.xml

buildDirStructure:

compileDiffXML:
    [javac] /home/masoud/diffxml-master/build.xml:74: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 39 source files to /home/masoud/diffxml-master/build

BUILD FAILED
/home/masoud/diffxml-master/build.xml:74: /home/masoud/diffxml-master/lib does not exist.

Total time: 0 seconds

**Comment by amouat** [comment]
That's a bug. I think I need to upload the libs. It would be better to use Maven or something, but I don't have time for that.

**Comment by meshkin** [comment]
yes, it works by diffxml.sh.
I have a question, and it is : why you didn't add the following line to Diff.xml?
Document diff(final Document f1, final Document f2) throws DiffException;

**Comment by amouat** [comment]
I'm afraid I really don't understand the question. Can I close this? It seems it works.

**Comment by meshkin** [comment]
Ok, however thanks for your useful module and your helps.

**Comment by amouat** [comment]
No problem. I'm glad you're finding a use for it.

**Comment by waiphyoMaung1990** [comment]
I aslo have a problem in below-
org.w3c.dom.DOMException: NAMESPACE_ERR: An attempt is made to create or change an object in a way which is incorrect with regard to namespaces.
	at java.xml/com.sun.org.apache.xerces.internal.dom.ElementNSImpl.setPrefix(ElementNSImpl.java:279)
	at com.sun.xml.messaging.saaj.soap.impl.ElementImpl.setPrefix(ElementImpl.java:252)
	at org.netbeans.modules.websvc.design.javamodel.Utils.setSoapRequest(Utils.java:575)
	at org.netbeans.modules.websvc.design.javamodel.Utils.populateOperation(Utils.java:497)
	at org.netbeans.modules.websvc.design.javamodel.Utils.access$100(Utils.java:109)
	at org.netbeans.modules.websvc.design.javamodel.Utils$1.run(Utils.java:352)
	at org.netbeans.modules.websvc.design.javamodel.Utils$1.run(Utils.java:173)
	at org.netbeans.api.java.source.JavaSource$MultiTask.run(JavaSource.java:504)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:132)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:116)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.runWhenScanFinished(RunWhenScanFinishedSupport.java:123)
	at org.netbeans.modules.parsing.api.ParserManager.parseWhenScanFinished(ParserManager.java:109)
	at org.netbeans.api.java.source.JavaSource.runWhenScanFinished(JavaSource.java:630)
	at org.netbeans.modules.websvc.design.javamodel.Utils.populateModel(Utils.java:366)
	at org.netbeans.modules.websvc.design.javamodel.ServiceModel.populateModel(ServiceModel.java:360)
	at org.netbeans.modules.websvc.design.javamodel.ServiceModel.<init>(ServiceModel.java:76)
	at org.netbeans.modules.websvc.design.javamodel.ServiceModel.getServiceModel(ServiceModel.java:83)
	at org.netbeans.modules.websvc.design.navigator.WSDesignViewNavigatorContent$WSChildFactory.createKeys(WSDesignViewNavigatorContent.java:103)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:202)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
